name: HealthCheckr.Body

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: 6.0.x
  OUTPUT_PATH: ${{ github.workspace }}/.output
  COVERAGE_PATH: ${{ github.workspace }}/.coverage
  COVERAGE_LOCATION: ${{ github.workspace }}/.coverage

on:
  push:
    branches:
      - main
    paths:
      - HealthCheckr.Body/**
  workflow_dispatch:

jobs:
  
  deploy-sql-tables:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v2
      - name: 'Deploy Azure SQL Tables'
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION }}
          path: './HealthCheckr.Body/src/HealthCheckr.Body/HealthCheckr.Body.Sql/HealthCheckr.Body.Sql/HealthCheckr.Body.Sql.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'

  