name: HealthCheckr.Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - HealthCheckr.Infrastructure/**
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Bicep Linter
        run: az bicep build --file ./HealthCheckr.Infrastructure/main.bicep

  validate:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./HealthCheckr.Infrastructure/main.bicep
          parameters: ./HealthCheckr.Infrastructure/parameters.prod.json emailAddress=${{ secrets.EMAIL_ADDRESS }}
          deploymentMode: Validate

  preview:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/cli@v1
        name: Run what-if
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ secrets.AZURE_RG }} --template-file ./HealthCheckr.Infrastructure/main.bicep --parameters ./HealthCheckr.Infrastructure/parameters.prod.json emailAddress=${{ secrets.EMAIL_ADDRESS }}
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    needs: preview
    steps:
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy Bicep File
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./HealthCheckr.Infrastructure/main.bicep
          parameters: ./HealthCheckr.Infrastructure/parameters.prod.json emailAddress=${{ secrets.EMAIL_ADDRESS }}
          failOnStdErr: false